In [4]:
import numpy as np

### Arrays are classes in numpy, where each array is an instance; and it has a fixated memory allocated (when merging, we a re creating a new one).
Arrays are created in two ways:
- By giving to the np.array() method the typical enumerative object in Python, i.e., lists.
- By using special numpy methods such as np.ones, np.zeros and np.empty arrays.

In [15]:
np.zeros(2)

array([0., 0.])

In [16]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

### .shape is another method in the class of the arrays:
.shape gives tuples, and tuples are needed in the declaration of np.ones, np.zeros and np.empty arrays.

In [17]:
b = a.shape

In [12]:
np.zeros(b)

array([[0., 0., 0.],
       [0., 0., 0.]])

### Each assignation of an array only shares the pointer, but does not modify the array!

In [45]:
a = np.array([1,2,3])
b = a
b[1] = 10

In [46]:
print(a)
print(b)

[ 1 10  3]
[ 1 10  3]


### We should do instead:

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 10

In [29]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a < 7]

array([1, 2, 3, 4, 5, 6])

In [30]:
a1 = np.array([[1, 1],

               [2, 2]])

a2 = np.array([[3, 3],

               [4, 4]])

In [31]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [32]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

![hey](broadcast.png)

In [56]:
# np.swapaxes( array, first axes to change, second axes to change)

### How to write the help information

In [57]:
def fct(x):
    """This info pops up when calling help"""
    return

In [58]:
fct(2)

In [55]:
help(fct)

Help on function fct in module __main__:

fct(x)
    This info pops up when calling help



![hey](matplot.png)